name: Build and Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Use a custom theme for quartz from "https://github.com/saberzero1/quartz-themes"
env:
  THEME_NAME: obsidian-gruvbox
  
permissions:
  contents: read
  deployments: write

concurrency:
  group: cloudflare-pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Fetch Quartz Theme
        run: curl -s -S https://raw.githubusercontent.com/saberzero1/quartz-themes/master/action.sh | bash -s -- $THEME_NAME

      - name: Build Quartz
        run: npx quartz build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: pages deploy public --project-name=${{ vars.CLOUDFLARE_PAGES_PROJECT_NAME }}
